import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

def sendemail(from_email, password, to_email, subject, message):
    msg = MIMEMultipart()
    msg['From'] = from_email
    msg['To'] = to_email
    msg['Subject'] = subject
    
    msg.attach(MIMEText(message, 'plain'))
    try:
        server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
        server.ehlo()
        server.login(from_email, password)
        server.sendmail(from_email, to_email, msg.as_string())
        server.close()
        return True
    except Exception as e:
        print('something went wrong: ' + str(e))
        return False

sendemail('jszhang0001@gmail.com', 'xxxxxxxxx','richardjiasheng@gmail.com','Test email','this is a test email.')    
#xxxxxx is the app password generated by gmail.


# smtp: simple mail transfer protocol to send emails

# pop3 vs imap: protocals to retrieve email from an email server